language: java
env:
  global:
  - secure: "LpcQ9attbY5AM742C0t20uyAUsCroByAQPsesMPITAnhAYj/sGMtnWFWyqTjTtAtptJFKFxihG7H218uJbHgqnit1c9brFWsbwCvxeLOmMmryAq4JfYEBZtno5oiMqIJtRKNuFPxlKrw6eOZk/zop1alDGzDmjH/oXqWlPCbjxI="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
